- hosts: rnfront
  become: true
  tasks:
    - name: Install Git 
      apt:
        name: git
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: apt update
      apt:
        update_cache: yes

    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: nginx start and enable
      systemd:
        name: nginx
        state: started
        enabled: yes



